class ShampooRunner{
 public static void main(String s[]){ 
 Shampoo ref=new Shampoo();
 ref.brandName="chik shampoo";
 ref.quantity="50g";
 ref.type="hair wash";
 ref.price=100.00;
 ref.mgfDate="11/05/1999";
 ref.expDate="15/09/2023";
 System.out.println("shampoo name is:"+ref.brandName);
 System.out.println("qty of shampoo is:"+ref.quantity);
 System.out.println("type of shampoo:"+ref.type);
 System.out.println("shampoo price is:"+ref.price);
 System.out.println("mgfDate:"+ref.mgfDate);
 System.out.println("expDate of shampoo:"+ref.expDate);
 System.out.println("---------------------------");
 Shampoo ref1=new Shampoo();
 ref1.brandName="sunsilk shampoo";
 ref1.quantity="100g";
 ref1.type="hair wash";
 ref1.price=200.00;
 ref1.mgfDate="6/09/2000";
 ref1.expDate="12/7/2002";
 System.out.println("shampoo name is:"+ref1.brandName);
 System.out.println("qty of shampoo:"+ref1.quantity);
 System.out.println("type is:"+ref1.type);
 System.out.println("shampoo price:"+ref1.price);
 System.out.println("mgfdate:"+ref1.mgfDate);
 System.out.println("expDate:"+ref1.expDate);
 System.out.println("*********************************");
 Shampoo wash=new Shampoo();
 wash.brandName="dov shampoo";
 wash.quantity="150g";
 wash.type="hair wash";
 wash.price=166.00;
 wash.mgfDate="26/11/2001";
 wash.expDate="12/2/2003";
 System.out.println("shampoo name is:"+wash.brandName);
 System.out.println("qty of shampoo:"+wash.quantity);
 System.out.println("type is:"+wash.type);
 System.out.println("shampoo price:"+wash.price);
 System.out.println("mgfdate:"+wash.mgfDate);
 System.out.println("expDate:"+wash.expDate);
 System.out.println("*********************************");
 Shampoo ref2=new Shampoo();
 ref2.brandName="Pantene";
 ref2.quantity="100g";
 ref2.type="hair wash";
 ref2.price=90.00;
 ref2.mgfDate="1/3/2007";
 ref2.expDate="10/5/2010";
 System.out.println("shampoo name is:"+ref2.brandName);
 System.out.println("qty of shampoo:"+ref2.quantity);
 System.out.println("type is:"+ref2.type);
 System.out.println("shampoo price:"+ref2.price);
 System.out.println("mgfdate:"+ref2.mgfDate);
 System.out.println("expDate:"+ref2.expDate);
 System.out.println("*********************************");
 Shampoo ref3=new Shampoo();
 ref3.brandName="Head & Shoulders";
 ref3.quantity="50g";
 ref3.type="hair wash";
 ref3.price=35.00;
 ref3.mgfDate="9/4/2012";
 ref3.expDate="15/7/2015";
 System.out.println("shampoo name is:"+ref3.brandName);
 System.out.println("qty of shampoo:"+ref3.quantity);
 System.out.println("type is:"+ref3.type);
 System.out.println("shampoo price:"+ref3.price);
 System.out.println("mgfdate:"+ref3.mgfDate);
 System.out.println("expDate:"+ref3.expDate);
 System.out.println("*********************************");
  Shampoo ref4=new Shampoo();
  ref4.brandName="Herbal Essences";
  ref4.quantity="100g";
  ref4.type="hair wash";
 ref4.price=199.00;
 ref4.mgfDate="19/4/2020";
 ref4.expDate="1/7/2021";
 System.out.println("shampoo name is:"+ref4.brandName);
 System.out.println("qty of shampoo:"+ref4.quantity);
 System.out.println("type is:"+ref4.type);
 System.out.println("shampoo price:"+ref4.price);
 System.out.println("mgfdate:"+ref4.mgfDate);
 System.out.println("expDate:"+ref4.expDate);
 System.out.println("*********************************");
 Shampoo ref5=new Shampoo();
  ref5.brandName="Garnier";
  ref5.quantity="350g";
  ref5.type="hair wash";
 ref5.price=400.00;
 ref5.mgfDate="2/10/2020";
 ref5.expDate="10/7/2021";
 System.out.println("shampoo name is:"+ref5.brandName);
 System.out.println("qty of shampoo:"+ref5.quantity);
 System.out.println("type is:"+ref5.type);
 System.out.println("shampoo price:"+ref5.price);
 System.out.println("mgfdate:"+ref5.mgfDate);
 System.out.println("expDate:"+ref5.expDate);
 System.out.println("*********************************");
 Shampoo wash1=new Shampoo();
  wash1.brandName="Schwarzkopf";
 wash1.quantity="380g";
  wash1.type="hair wash";
 wash1.price=500.00;
 wash1.mgfDate="2/10/2020";
 wash1.expDate="10/7/2021";
 System.out.println("shampoo name is:"+wash1.brandName);
 System.out.println("qty of shampoo:"+wash1.quantity);
 System.out.println("type is:"+wash1.type);
 System.out.println("shampoo price:"+wash1.price);
 System.out.println("mgfdate:"+wash1.mgfDate);
 System.out.println("expDate:"+wash1.expDate);
 System.out.println("*********************************");
 Shampoo wash2=new Shampoo();
  wash2.brandName="L'Oréal Paris";
 wash2.quantity="140g";
  wash2.type="hair wash";
 wash2.price=199.00;
 wash2.mgfDate="20/1/2015";
 wash2.expDate="22/9/2016";
 System.out.println("shampoo name is:"+wash2.brandName);
 System.out.println("qty of shampoo:"+wash2.quantity);
 System.out.println("type is:"+wash2.type);
 System.out.println("shampoo price:"+wash2.price);
 System.out.println("mgfdate:"+wash2.mgfDate);
 System.out.println("expDate:"+wash2.expDate);
 System.out.println("*********************************");

 
 Shampoo wash0=new Shampoo();
  wash0.brandName="TRESemmé";
 wash0.quantity="140g";
  wash0.type="hair wash";
 wash0.price=199.00;
 wash0.mgfDate="20/1/2015";
 wash0.expDate="22/9/2016";
 System.out.println("shampoo name is:"+wash0.brandName);
 System.out.println("qty of shampoo:"+wash0.quantity);
 System.out.println("type is:"+wash0.type);
 System.out.println("shampoo price:"+wash0.price);
 System.out.println("mgfdate:"+wash0.mgfDate);
 System.out.println("expDate:"+wash0.expDate);
 System.out.println("*********************************");
 Shampoo ref8=new Shampoo();
   ref8.brandName="Clinic plus";
   ref8.quantity="5";
   ref8.type="Thick Hair";
   ref8.price=20.00;
   ref8.mgfDate="3/6/24";
   ref8.expDate="4/4/30"; 
   System.out.println("The name is"+ref8.brandName);
   System.out.println("The Quantity is "+ ref8.quantity);
   System.out.println("The type is"+ref8.type);
   System.out.println("The Price is "+ref8.price);
   System.out.println("The manufacture Date is "+ref8.mgfDate);
	  System.out.println("The Expire Date is"+ref8.expDate);
	  
   Shampoo ref9=new Shampoo();
   ref9.brandName="Chick";
   ref9.quantity="50";
   ref9.type="Long Hair";
   ref9.price=20;
   ref9.mgfDate="3/6/14";
   ref9.expDate="4/4/20";
   
   System.out.println("The name is"+ref9.brandName);
   System.out.println("The Quantity is "+ ref9.quantity);
    System.out.println("The type is"+ref9.type);
	System.out.println("The Price is "+ref9.price);
   System.out.println("The manufacture Date is "+ref9.mgfDate);
	  System.out.println("The Expire Date is"+ref9.expDate);
	  
	  Shampoo ref14=new Shampoo();
	ref14.brandName="Vatika";
   ref14.quantity="5";
   ref14.type="Thick Hair";
   ref14.price=2.00;
   ref14.mgfDate="3/6/24";
   ref14.expDate="4/4/30";
   
   System.out.println("The name is"+ref14.brandName);
   System.out.println("The Quantity is "+ ref14.quantity);
    System.out.println("The type is"+ref14.type);
	System.out.println("The Price is "+ref14.price);
	 System.out.println("The manufacture Date is "+ref14.mgfDate);
	  System.out.println("The Expire Date is"+ref14.expDate);
	  System.out.println("The Expire Date is"+ref14.expDate);
	  
  Shampoo ref12=new Shampoo();
	ref12.brandName="Wow";
   ref12.quantity="500g";
   ref12.type="Thick Hair";
   ref12.price=200.00;
   ref12.mgfDate="3/6/24";
   ref12.expDate="4/4/30";
   
   System.out.println("The name is"+ref12.brandName);
   System.out.println("The Quantity is "+ ref12.quantity);
    System.out.println("The type is"+ref12.type);
	System.out.println("The Price is "+ref12.price);
	 System.out.println("The manufacture Date is "+ref12.mgfDate);
	  System.out.println("The Expire Date is"+ref12.expDate);
	  
	  Shampoo ref13=new Shampoo();
	ref13.brandName="Plum";
   ref13.quantity="60";
   ref13.type="Long and Healty Hair";
   ref13.price=148.00;
   ref13.mgfDate="3/6/24";
   ref13.expDate="4/4/30";
   
   System.out.println("The name is"+ref13.brandName);
   System.out.println("The Quantity is "+ ref13.quantity);
    System.out.println("The type is"+ref13.type);
	System.out.println("The Price is "+ref13.price);
	 System.out.println("The manufacture Date is "+ref13.mgfDate);
	  System.out.println("The Expire Date is"+ref13.expDate);
	  
	  Shampoo ref11=new Shampoo();
	ref11.brandName="MamaEarth ";
   ref11.quantity="500";
   ref11.type="Anti HairFall";
   ref11.price=800.00;
   ref11.mgfDate="3/6/24";
   ref11.expDate="4/4/30";
   
   System.out.println("The name is"+ref11.brandName);
   System.out.println("The Quantity is "+ ref11.quantity);
    System.out.println("The type is"+ref11.type);
	System.out.println("The Price is "+ref11.price);
	 System.out.println("The manufacture Date is "+ref11.mgfDate);
	  System.out.println("The Expire Date is"+ref11.expDate);
 } 
}